import React from 'react';
import { BadgeVisualVariant } from '../../types/ui';

interface StatusBadgeProps {
  variant: BadgeVisualVariant;
  customLabel?: string;
  size?: 'sm' | 'md';
}

export const StatusBadge: React.FC<StatusBadgeProps> = ({ variant, customLabel, size = 'md' }) => {
  const getBadgeConfig = () => {
    switch (variant) {
      case 'ai':
        return {
          symbol: '✦',
          label: customLabel || 'AI generated',
          color: 'var(--status-ai-color)',
          bg: 'var(--status-ai-bg)',
          border: 'var(--status-ai-border)',
          tooltip: 'Draft generated by AI pipeline'
        };
      case 'source':
        return {
          symbol: '⛓',
          label: customLabel || 'Source matched',
          color: 'var(--status-source-color)',
          bg: 'var(--status-source-bg)',
          border: 'var(--status-source-border)',
          tooltip: 'Factual claim linked directly to source document'
        };
      case 'passed':
        return {
          symbol: '●',
          label: customLabel || 'Rule passed',
          color: 'var(--status-passed-color)',
          bg: 'var(--status-passed-bg)',
          border: 'var(--status-passed-border)',
          tooltip: 'Passed deterministic rules engine verification'
        };
      case 'approved':
        return {
          symbol: '✓',
          label: customLabel || 'Human approved',
          color: 'var(--status-approved-color)',
          bg: 'var(--status-approved-bg)',
          border: 'var(--status-approved-border)',
          tooltip: 'Verified and signed off by lead reviewer'
        };
      case 'review':
        return {
          symbol: '▲',
          label: customLabel || 'Review required',
          color: 'var(--status-review-color)',
          bg: 'var(--status-review-bg)',
          border: 'var(--status-review-border)',
          tooltip: 'Requires manual human inspection or clarification'
        };
      case 'failed':
        return {
          symbol: '✕',
          label: customLabel || 'Rule failed',
          color: 'var(--status-failed-color)',
          bg: 'var(--status-failed-bg)',
          border: 'var(--status-failed-border)',
          tooltip: 'Violates regulatory constraints or missing mandatory clause'
        };
      case 'superseded':
        return {
          symbol: '↺',
          label: customLabel || 'Superseded',
          color: 'var(--status-superseded-color)',
          bg: 'var(--status-superseded-bg)',
          border: 'var(--status-superseded-border)',
          tooltip: 'Replaced by a newer document redline or revised claim'
        };
      case 'certified':
        return {
          symbol: '◈',
          label: customLabel || 'Certified',
          color: 'var(--status-certified-color)',
          bg: 'var(--status-certified-bg)',
          border: 'var(--status-certified-border)',
          tooltip: 'Cryptographically certified and version locked'
        };
    }
  };

  const config = getBadgeConfig();
  const isSm = size === 'sm';

  return (
    <span
      title={config.tooltip}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: isSm ? '4px' : '6px',
        padding: isSm ? '2px 6px' : '4px 9px',
        borderRadius: 'var(--radius-sm)',
        fontSize: isSm ? '11px' : '12px',
        fontWeight: 600,
        color: config.color,
        backgroundColor: config.bg,
        border: `1px solid ${config.border}`,
        fontFamily: 'var(--font-sans)',
        whiteSpace: 'nowrap',
        cursor: 'help'
      }}
    >
      <span style={{ fontSize: isSm ? '10px' : '12px', lineHeight: 1 }}>{config.symbol}</span>
      <span>{config.label}</span>
    </span>
  );
};
